---
- hosts: myServers
  become: yes
  tasks: 
    - name: Installs Nginx
      apt: pkg=nginx state=present update_cache=true
      notify:
       - start: nginx
    - name: start Nginx
      service: name=nginx state=started
